#!/usr/bin/env bash
#
# Set up the boreas-windows development environment.
#
# Installs the .NET SDK this repository pins into one directory, contains
# every side effect inside it, and writes an env.sh to source. Re-running is
# safe and cheap.
#
#   ./.agents/skills/setup-boreas-windows/scripts/setup.sh
#   source "${TMPDIR:-/tmp}/boreas-windows-dev/env.sh"
#
# There is no architecture list and no operating-system list anywhere in this
# script, deliberately. dotnet-install.sh detects both, and a second detector
# here would be a competing answer to a question upstream already answers, on
# a narrower table: upstream also knows musl, FreeBSD, s390x, ppc64le and
# riscv64. Whatever it supports, this supports, and no platform is privileged
# because none is named.
#
# Assumes bash 3.2 or later (the macOS system bash) and POSIX coreutils. No
# GNU-only flags, no bash 4 constructs.
set -euo pipefail

readonly INSTALLER_URL="https://dot.net/v1/dotnet-install.sh"
readonly SIGNATURE_URL="https://dot.net/v1/dotnet-install.sig"
readonly PUBLIC_KEY_URL="https://dot.net/v1/dotnet-install.asc"

# Written into the root at install time. --uninstall refuses to remove a
# directory without it, so a mistyped --root cannot turn into rm -rf on
# something this script never created.
readonly MARKER=".boreas-windows-dev"

warn() { printf '%s\n' "$*" >&2; }
die() { warn "error: $*"; exit 1; }

usage() {
  cat <<'USAGE'
usage: setup.sh [options]

  --root DIR     where the toolchain lives (default: ${TMPDIR:-/tmp}/boreas-windows-dev)
  --check        also build and run the core law suite
  --uninstall    remove the toolchain root and exit
  --no-verify    skip the installer signature check (not recommended)
  --help         this text

Sourcing DIR/env.sh puts the toolchain on PATH for the current shell.
USAGE
}

# The repository is found from this script's own location rather than from the
# working directory, so the command above works when pasted from anywhere.
resolve_repository() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null \
    || die "not inside a git repository: $script_dir"
}

# Fetch the installer and prove it is the one Microsoft signed. GNUPGHOME is
# inside the root, so importing the key does not touch the user's keyring.
fetch_installer() {
  local work="$1" verify="$2"

  curl -fsSL -o "$work/dotnet-install.sh" "$INSTALLER_URL"

  if [ "$verify" != "true" ]; then
    warn "warning: installer signature not checked (--no-verify)"
    return 0
  fi

  command -v gpg >/dev/null 2>&1 \
    || die "gpg not found. Install it, or re-run with --no-verify to accept an unverified installer."

  curl -fsSL -o "$work/dotnet-install.sig" "$SIGNATURE_URL"
  curl -fsSL -o "$work/dotnet-install.asc" "$PUBLIC_KEY_URL"

  GNUPGHOME="$work/gnupg"
  export GNUPGHOME
  mkdir -p "$GNUPGHOME"
  chmod 700 "$GNUPGHOME"

  gpg --quiet --import "$work/dotnet-install.asc"
  gpg --verify "$work/dotnet-install.sig" "$work/dotnet-install.sh" 2>/dev/null \
    || die "installer signature did not verify. Do not run it."
}

# The SDK's own resolver decides whether what is installed satisfies
# global.json: it reads the file and fails when nothing matches. Asking it
# beats parsing the pin here and re-implementing rollForward.
satisfies_pin() {
  local dotnet="$1" repo="$2"
  [ -x "$dotnet" ] || return 1
  (cd "$repo" && "$dotnet" --version) >/dev/null 2>&1
}

# --jsonfile takes the version from the pin the repository already states, so
# the installed SDK cannot drift from it. No --architecture and no --os: both
# default to detecting the running machine.
install_sdk() {
  local installer="$1" repo="$2" root="$3"
  bash "$installer" \
    --jsonfile "$repo/global.json" \
    --install-dir "$root/dotnet" \
    --no-path
}

# Written by generation rather than by hand so it cannot drift from the root
# it describes. POSIX sh, because the shell sourcing it may be zsh, and
# rewritten atomically so a reader never sees a half-written file.
write_environment() {
  local root="$1" tmp="$1/.env.sh.partial"

  cat >"$tmp" <<'PROLOGUE'
# Generated by setup.sh. Source this file; do not execute it.
PROLOGUE

  cat >>"$tmp" <<PATHS
BOREAS_DEV_ROOT="$root"
PATHS

  cat >>"$tmp" <<'BODY'
export DOTNET_ROOT="$BOREAS_DEV_ROOT/dotnet"

# Contain the rest of the toolchain's state. Without these, packages land in
# $HOME/.nuget and first-run sentinels in $HOME/.dotnet, and removing the root
# would no longer remove everything this environment created.
export NUGET_PACKAGES="$BOREAS_DEV_ROOT/nuget"
export DOTNET_CLI_HOME="$BOREAS_DEV_ROOT/cli-home"

export DOTNET_NOLOGO=true
export DOTNET_CLI_TELEMETRY_OPTOUT=true

# A generated executable prefers DOTNET_ROOT_<ARCH> over DOTNET_ROOT, so one
# inherited from an earlier install silently wins over the line above and the
# runtime is looked for in the wrong place. Clearing the family is the fix
# that needs no architecture name: whichever member was set, it is gone, and
# DOTNET_ROOT is left as the only answer.
unset DOTNET_ROOT_X64 DOTNET_ROOT_X86 DOTNET_ROOT_ARM64 DOTNET_ROOT_ARM
unset "DOTNET_ROOT(x86)" 2>/dev/null || true

# Idempotent: sourcing twice must not stack two copies on PATH.
case ":$PATH:" in
  *":$DOTNET_ROOT:"*) ;;
  *) PATH="$DOTNET_ROOT:$PATH" ;;
esac
export PATH
BODY

  mv "$tmp" "$root/env.sh"
}

uninstall() {
  local root="$1"
  [ -d "$root" ] || { printf 'nothing to remove at %s\n' "$root"; return 0; }
  [ -f "$root/$MARKER" ] \
    || die "$root has no $MARKER file, so setup.sh did not create it. Refusing to remove it."
  rm -rf "$root"
  printf 'removed %s\n' "$root"
}

main() {
  local root="${TMPDIR:-/tmp}/boreas-windows-dev"
  local check="false" verify="true" action="install"

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --root) root="${2:?--root needs a directory}"; shift 2 ;;
      --check) check="true"; shift ;;
      --uninstall) action="uninstall"; shift ;;
      --no-verify) verify="false"; shift ;;
      --help|-h) usage; return 0 ;;
      *) usage >&2; die "unknown option: $1" ;;
    esac
  done

  # Trailing slashes and relative paths both reach rm -rf and the generated
  # env.sh, so normalise once here and treat it as trusted below.
  mkdir -p "$root"
  root="$(cd "$root" && pwd)"

  if [ "$action" = "uninstall" ]; then
    uninstall "$root"
    return 0
  fi

  local repo
  repo="$(resolve_repository)"
  [ -f "$repo/global.json" ] || die "no global.json at $repo"

  if satisfies_pin "$root/dotnet/dotnet" "$repo"; then
    printf 'SDK already satisfies %s/global.json\n' "$repo"
  else
    local work
    work="$(mktemp -d)"
    # shellcheck disable=SC2064  # $work is expanded now on purpose.
    trap "rm -rf '$work'" EXIT

    fetch_installer "$work" "$verify"
    install_sdk "$work/dotnet-install.sh" "$repo" "$root"

    satisfies_pin "$root/dotnet/dotnet" "$repo" \
      || die "installed SDK does not satisfy $repo/global.json"
  fi

  printf '%s\n' "$MARKER" >"$root/$MARKER"
  write_environment "$root"

  # Reported by the toolchain rather than guessed here, for the same reason
  # the platform is not detected here.
  local rid
  rid="$("$root/dotnet/dotnet" --info | awk -F': *' '/^ *RID:/ { print $2; exit }')"
  printf 'ready: .NET %s (%s) in %s\n' \
    "$(cd "$repo" && "$root/dotnet/dotnet" --version)" "$rid" "$root"

  if [ "$check" = "true" ]; then
    # shellcheck source=/dev/null
    . "$root/env.sh"
    dotnet test "$repo/tests/Boreas.Ui.Tests/Boreas.Ui.Tests.csproj" --configuration Release
  fi

  printf '\nnext:\n  source %s/env.sh\n' "$root"
}

main "$@"
